name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: build
      - uses: actions/checkout@v2
        run: ci/build-app.sh
      - name: Test
        run: ci/test-app.sh